### ISSUE TITLE
getSoilClay (and SOM/C too)

### ISSUE THREAD

**Issue by kendalynnm** [COMPASS-DOE/rs-synthesis#50]
Hi Ben,
Please have a go at extracting clay and SOM content from soil grids. My code attempt is in the getSoilClay.R file currently in the draft merge between KM_modeltweaks and main.
Thank you!
Kendal

**Comment by bpbond** [comment]
Notes to self

https://git.wur.nl/isric/soilgrids/soilgrids.notebooks/-/blob/master/markdown/webdav_from_R.md

https://rpubs.com/ials2un/soilgrids_webdav

**Comment by kendalynnm** [comment]
Issued resolved, branch now merged with main
