### ISSUE TITLE
run-up to submission clean-up

### ISSUE THREAD

**Issue by kendalynnm** [COMPASS-DOE/rs-synthesis#60]
Hi Ben, if you have time I've got three asks of you:

1) I would like to have information on ecosystem and manipulation type in the study table that you made, however it currently generates new rows for any studies with more than one ecosystem/manipulation. Would you please use the Force to create new categories for these cases. For studies with both manipulation types, I think a "both" category is easiest. For studies with more than one ecosystem, a list would probably be best.

2) You may have already noticed that there's an issue with the yaml render, it's something new possibly in addition to the relatively straightforward fix of adding new packages. When you have a moment, would you please take a look?

3) Actually it might have only been two asks...

...for now... >_<

**Comment by bpbond** [comment]
Hi @kendalynnm , re these

1. Sorry—I'm confused what you're asking for here.
2. See my [comment in the PR](https://github.com/COMPASS-DOE/rs-synthesis/pull/61/#issuecomment-1049408434).

**Comment by kendalynnm** [comment]
Hi @bpbond,

1. To recap what we discussed Friday, see the example of Borken et al 1999 below - there's one observation for Drought and one for Irrigation. I'd like for this to be one row with two observations with the words Drought and Irrigation both appearing in the Manipulation column. Same idea of Inglima et al 2009 with three ecosystems, should be one row with three obersvations and all three ecosystems appearing as a short list in the Ecosystem_type column.

2. I'm working on it, let's talk tomorrow.


ID | Authors | DOI | Observations | Ecosystem_type | Manipulation
1268 | Billings et al. (1998) | 10.1139/x98-145 | 4 | Forest | Drought
1421 | Borken et al. (1999) | 10.2136/sssaj1999.6361848x | 1 | Forest | Drought
1421 | Borken et al. (1999) | 10.2136/sssaj1999.6361848x | 1 | Forest | Irrigation
1639 | Maier et al. (2000) | 10.1139/x99-218 | 2 | Forest | Irrigation
4849 | Garten et al. (2009) | 10.1007/s11104-008-9851-6 | 2 | Grassland | Drought
4895 | Inglima et al. (2009) | 10.1111/j.1365-2486.2008.01793.x | 1 | Forest | Irrigation
4895 | Inglima et al. (2009) | 10.1111/j.1365-2486.2008.01793.x | 1 | Shrubland | Irrigation
4895 | Inglima et al. (2009) | 10.1111/j.1365-2486.2008.01793.x | 1 | Grassland | Irrigation

**Comment by bpbond** [comment]
@kendalynnm Re drought and irrigation, how's this?

ID | Authors | DOI | Ecosystem_type | Drought | Irrigation
-- | -- | -- | -- | -- | --
1268 | Billings et al. (1998) | 10.1139/x98-145 | Forest | 4 | 0
1421 | Borken et al. (1999) | 10.2136/sssaj1999.6361848x | Forest | 1 | 1
1639 | Maier et al. (2000) | 10.1139/x99-218 | Forest | 0 | 2

**Comment by bpbond** [comment]
>Same idea of Inglima et al 2009 with three ecosystems, should be one row with three obersvations and all three ecosystems appearing as a short list in the Ecosystem_type column.

Hmm. So Inglima has 1 shrubland drought and 1 grassland drought. If we now have "drought" and "irrigation" columns, as above, how do you want this to appear?

**Comment by kendalynnm** [comment]
Hmm, I see. I'd like to avoid new columns for Ecosystems (and the manipulations too, if possible). Is it possible to make a string of the unique levels of Ecosystem_type from one study number and print that list in the study's row?

**Comment by bpbond** [comment]
How's this:



ID | Authors | DOI | Ecosystem_type | Drought | Irrigation
-- | -- | -- | -- | -- | --
1268 | Billings et al. (1998) | 10.1139/x98-145 | Forest | 4 | 0
1421 | Borken et al. (1999) | 10.2136/sssaj1999.6361848x | Forest | 1 | 1
4895 | Inglima et al. (2009) | 10.1111/j.1365-2486.2008.01793.x | Forest, Shrubland, Grassland | 0 | 3

**Comment by bpbond** [comment]
@kendalynnm re (2) above, I have pushed a change to #61 that I think will clear up the problem.
