### ISSUE TITLE
original article data pull

### ISSUE THREAD

**Issue by kendalynnm** [COMPASS-DOE/rs-synthesis#65]
Hi Ben,
As we discussed, the 82 studies used in the final analysis (see table from Rmarkdown output) should be combed for the following information:

- Soil clay content (as % or per unit mass) and relevant depth increment for that content
- Soil organic carbon content (as % or per unit mass) and relevant depth increment for that content
- Soil moisture content (averaged for treatment & control) or %increase/decrease with treatment and relevant depth increment for measurement

This could be gathered as a separate spreadsheet with study number are the organizing ID column, or by adding the information to the existing Google sheet.

Please feel free to flag ambiguous cases for follow-up by myself. Thank you very much for your help with this!

**Comment by bpbond** [comment]
See #66 - pausing this work until we can discuss. Branch is [here](https://github.com/COMPASS-DOE/rs-synthesis/tree/bpbond-patch-1).
