### ISSUE TITLE
13000 Ohashi

### ISSUE THREAD

**Issue by bpbond** [COMPASS-DOE/rs-synthesis#66]
@kendalynnm 

In your studies table, there is "13000 Ohashi":
<img width="697" alt="Screen Shot 2022-05-23 at 3 07 06 PM" src="https://user-images.githubusercontent.com/1956468/169889216-f1598bbb-67d0-490d-ba52-53584b5969d2.png">

This DOI resolves to [this paper](https://link.springer.com/article/10.1007/s11104-018-03929-3) that took place in a tropical rainforest, not a grassland; the latitude and longitude don't match what's in the main data sheet for study 13000. Not sure what to do here; I guess skipping for now.

**Comment by bpbond** [comment]
Oh wait. This is confusing.

In the "Rs Studies 2018+ - Water Manipulation.csv" file, 13000 is listed with a different DOI that's this paper: https://www.publish.csiro.au/rj/RJ16083

...and the lat/lon do match what's in the table. OK, I am putting a pin in this until we can discuss tomorrow.

**Comment by kendalynnm** [comment]
Hi @bpbond,

Are you on the current main branch? We found some issues with DOIs before submitting, and I manually checked and corrected in this [commit](https://github.com/COMPASS-DOE/rs-synthesis/commit/5d448111f591081a9384c501f552f8040d1c5433).

See also, this issue for SRDB: https://github.com/bpbond/srdb/issues/135#issue-1157776328
